language: node_js
sudo: required
node_js:
  - stable
before_install:
  - export TZ='Asia/Tokyo'
  - npm install hexo-cli -g
  - npm install -- save-dev hexo-util
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_script:
  - git config --global user.name "nickcheng"
  - git config --global user.email "n@nickcheng.com"
  - git clone https://${GH_Ref} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i'' "s~${GH_Ref}~${GH_Token}:x-oauth-basic@${GH_Ref}~" _config.yml
  - hexo d > log.txt 2>&1
  - cat log.txt | sed "s~${GH_Token}~TOKEN~g"
branches:
  only:
    - admin
env:
  global:
    - GH_Ref: github.com/nickcheng/nickcheng.github.io.git
