language: node_js
sudo: required
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - git config --global push.default matching
  - git config --global user.name "nickcheng" 
  - git config --global user.email "n@nickcheng.com"
install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
script:
  - hexo clean
  - hexo generate
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GH_Token@github.com/nickcheng/nickcheng.github.io.git master
branches:
  only:
    - admin
