language: node_js
sudo: required
node_js:
  - stable
before_install:
  - export TZ='Asia/Tokyo'
  - npm install hexo-cli -g
  - npm install -- save-dev hexo-util
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_script:
  - git clone https://${GH_Ref} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "nickcheng"
  - git config user.email "n@nickcheng.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_Token}@${GH_Ref}" master:master
branches:
  only:
    - admin
env:
  global:
    - GH_Ref: github.com/nickcheng/nickcheng.github.io.git
